name: CI pipeline for Golang WebSerer

on: push

jobs:
    build: 
        runs-on: [self-hosted, Linux, X64, Laptop]

        steps:
            - uses: actions/checkout@v4

            - name: Run test
              run: |
                echo Add other actions to build,
                echo test, and deploy your project. 